### ISSUE TITLE
Add features like prestine, dirty, valid

### ISSUE THREAD

**Issue by salisuwy** [moeen-basra/ree-validate#1]
This is the best react validation library similar to angular and vee-validate.
Can you please add feature like:
Form: valid, prestine, dirty etc
Fields: prestine, valid, dirty etc
Thanks 

#### Versions:
- VueJs: #.#.#
- Vee-Validate:

**Comment by moeen-basra** [comment]
Thanks @salisuwy, I will try that in my free time.

**Comment by salisuwy** [comment]
Hello @moeen-basra. I've looked at the source code and noticed some field states such as dirty, touched, isvalid etc. Is there a guide on how one can assess these field states? Thanks

**Comment by moeen-basra** [comment]
I'll be writing detailed documentation soon. Actively working on its improvements.

**Comment by salisuwy** [comment]
Hello @moeen-basra. Any progress on the features you're adding? Thanks

**Comment by moeen-basra** [comment]
hi and sorry @salisuwy, I was little busy with my job was unable to create the docs. I'll surely update it soon.
