### ISSUE TITLE
How to validate object values

### ISSUE THREAD

**Issue by mnksingh1996** [moeen-basra/ree-validate#10]
#### Versions:
- ReactJs: #.#.#
- Ree-Validate:

### Description:
lets say we have an object
this.state = {
    a : { 
      name: "",
      age: ""
   }
}

So i can validate on blur but when i try to trigger this.validate.validateAll() it will miss those inside the objects.

**Comment by moeen-basra** [comment]
This is not supported yet you need to attach the fields you want to validate and on change you need to call the validate method on all or for specific field.
