### ISSUE TITLE
Regex Problem

### ISSUE THREAD

**Issue by FareedR** [moeen-basra/ree-validate#13]
#### Versions:
- ReactJs: ^16.11.0
- Ree-Validate: ^1.0.15

### Description:
why I get error when I set regex like this 
`this.validator = new Validator({
            avatar: '',
            phone_no: 'numeric|max:12',
            address: 'regex:^[a-zA-Z0-9\s\.\-\/,]+$',
            city: 'regex:^[a-zA-Z\s]+$',
            postcode: 'numeric',
            state: 'regex:^[a-zA-Z\s]+$',
            country: 'regex:^[a-zA-Z\s]+$'
        })`
this is example of test string on that regex https://regex101.com/r/tvUtu0/1

Error Occured :-
1. Uncaught SyntaxError: Invalid flags supplied to RegExp constructor ']+$' ( **IF I PUT REGEX ON COMMA** )
2. The address field format is invalid. ( **IF I PUT REGEX ^ ...... + $** )

**Comment by moeen-basra** [comment]
Please use the version 3.0.2

**Comment by amirulhakim47** [comment]
you may close this if it's resolved
