### ISSUE TITLE
ReeValidate.Validator is not a constructor

### ISSUE THREAD

**Issue by namnguyen2091** [moeen-basra/ree-validate#14]
#### Versions:
- ReactJs: 16.10.2
- Ree-Validate: 3.3.0
- webpack: 4.41.2

### Description:
Uncaught TypeError: ree_validate__WEBPACK_IMPORTED_MODULE_16__.default.Validator is not a constructor

### Steps To Reproduce:
this is step I use it:

> import ReeValidate from 'ree-validate';
> this.validator = new ReeValidate.Validator({
> 			company_nm: 'required',
> 			company_ab_nm: 'required',
> 			zipcode: 'required',
> 			address1: 'required',
> 			TEL: 'required',
> 			FAX: 'required',
> 		})
And sometime when I install this library, there are some files is missing in dist folder.

**Comment by moeen-basra** [comment]
@namnguyen2091 please stick with the version 3.0.2
