### ISSUE TITLE
Version 3.3.0 update not working

### ISSUE THREAD

**Issue by RobertOnyango** [moeen-basra/ree-validate#19]
#### Versions:
- ReactJs: #.#.#
- Ree-Validate: : ree-validate.esm.js does not exist

### Description:
Version 3.3.0 not working after update from 3.0.2

### Steps To Reproduce:
npm update ree-validate

**Comment by moeen-basra** [comment]
remove and reinstall the package

```npm r -S ree-validate```
```npm i -S ree-validate```
