### ISSUE TITLE
multiple field attach

### ISSUE THREAD

**Issue by lochawala** [moeen-basra/ree-validate#20]
#### Versions:
- ReactJs: 16.13.1
- Ree-Validate:3.3.1

### Description:
How can i attach multiple field at ones 

```
const field = {
    name: 'fieldName',
    alias: 'Field Name',
    rules: 'rules'
}

this.validator.attach(field)
```

or is there any way to add alias here 

```
this.validator = new ReeValidate.Validator({
            first_name: 'required|min:3',
})
```

**Comment by moeen-basra** [comment]
@lochawala you can create an array for fields and create a function and loop them through

```
const fields = [
  {
    name: 'fieldName',
    alias: 'Field Name',
    rules: 'rules'
  },
  {
    name: 'fieldName',
    alias: 'Field Name',
    rules: 'rules'
  }
]

attachFields() {
  fields.each((f) => {
    this.validator.attach(f)
  })
}

```

the better approach is to create an HOC just like in the readme and use that where ever you want.

**Comment by lochawala** [comment]
@moeen-basra  Thanks for replay 
yes i follow loop option for now

i have one another query can you please provide example how can we write custom validation for confirm field it's good if you provide it 

Thanks for reply and great plugin

**Comment by moeen-basra** [comment]
you can use something like this 

in constructor 

first, you have to register the value in validator maybe with no rules

```
onChange(e) {
 const name = e.target.name
 const value = e.target.value
 const { errors } = this.validator

 if (field === 'confirmedPassword') {
    if (value !== this.state.password) {
       errors.add(name, 'error message')
    } else {
     errors.remove(name)
   }

  this.setState({ errors })
  } 
}
```

**Comment by lochawala** [comment]
Thank you
