### ISSUE TITLE
missing "same" rule

### ISSUE THREAD

**Issue by Kepro** [moeen-basra/ree-validate#5]
#### Versions:
- ReactJs: 16.4.0
- Ree-Validate: 3.0.2

### Description:
same:field
The given field must match the field under validation.

### Steps To Reproduce:
Error: [ree-validate] No such validator 'same' exists.

I need compare password and confirm password

**Comment by moeen-basra** [comment]
all matching rules doesn't work at this point you need to do manually. I'm re writing this script purely for react and will soon be available.

Sorry for in convenience.
