### ISSUE TITLE
validateAll triggers all error messages in form

### ISSUE THREAD

**Issue by mnksingh1996** [moeen-basra/ree-validate#7]
#### Versions:
- ReactJs: #.#.#
- Ree-Validate:

### Description:
Checking for validation with validateAll triggers all error messages, I just need to check the form validity without triggering the error messages.
Also flags like touched, dirty isn't changing in this.validator object.

### Steps To Reproduce:
just use function
this.validate.validateAll(formdata).then(valid => console.log(valid));

**Comment by moeen-basra** [comment]
1. You can put fields bag in state just like the errors to track change in flags.

2. Error get generated automatically this is the default behaviour of the extension if you don't need to display the errors you can just remove the code under the input field/

**Comment by mnksingh1996** [comment]
@moeen-basra 
I need to show error of that particular field on blur.
and I need to track if the whole form is valid, which is am trying to do on componentDidUpdate but it triggers error messages as well.
Anyways tried putting the field bag inside my state like but it doesn't seem to update
this.state = {formData : {....}, errors : this.validator.errors , fields: this.validator.fields }

**Comment by moeen-basra** [comment]
after each validation you and get field bag from validator and put it back in state just like the error bag
