### ISSUE TITLE
Validating Dynamically added elements

### ISSUE THREAD

**Issue by mnksingh1996** [moeen-basra/ree-validate#8]
#### Versions:
- ReactJs: latest
- Ree-Validate: latest

### Description:
Currently i have an array of exams such as - 

examName - examScore -  Add/Delete

One can add more exams to the list along with thier score and remove or add them and i need to validate them. Right now we need to initialize the bag so i can't validate them dynamically.
Is there any alternative to this?

**Comment by moeen-basra** [comment]
you can use the attach method of validator
on add new exam 
`this.validator.attach({name: examName, rules: xxx})`

on remove
`this.validator.detach(examName)`
