### ISSUE TITLE
Cant set alias for names

### ISSUE THREAD

**Issue by mnksingh1996** [moeen-basra/ree-validate#9]
#### Versions:
- ReactJs: #.#.#
- Ree-Validate:

### Description:
for a field called creditTypeOrDuration, i want to show "credit type or duration" to user.

**Comment by moeen-basra** [comment]
you can do this 
```
const field = {
    name: 'fieldName',
    alias: 'Field Name',
    rules: 'rules'
}

this.validator.attach(field)
```
